# -*- coding: utf-8 -*-
"""Paule_Lab2 Modelling Process

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkO_TNe-zR89hrtLssnD4CpMMkHseNpO
"""

def traffic_flow(density, speed):
    return density * speed   # Flow = density × speed

# Test the function
k = 20   # cars per km
v = 80   # km/h
q = traffic_flow(k, v)
print("Traffic flow:", q, "cars/hour")

v_free = 100   # km/h
k_jam = 150    # cars/km

def speed_density(k):
    return v_free * (1 - k / k_jam) # Fill the blank

# Test with different values
for test_k in [0, 50, 100, 150]:
    print(f"k = {test_k}, speed = {speed_density(test_k)} km/h")

import numpy as np
import matplotlib.pyplot as plt

k_values = np.linspace(0, 150, 100)   # Density range
v_values = speed_density(k_values)    # Speeds
q_values = k_values * v_values        # Flow = density × speed

plt.plot(k_values, q_values, label="Flow-Density Curve")
plt.xlabel("Density (cars/km)")
plt.ylabel("Flow (cars/hour)")
plt.title("Fundamental Diagram of Traffic Flow")
plt.legend()
plt.grid(True)
plt.show()

max_flow = np.max(q_values)
best_density = k_values[np.argmax(q_values)]
print("Maximum flow =", max_flow, "cars/hour")
print("Best density =", best_density, "cars/km")