# -*- coding: utf-8 -*-
"""Paule_Lab2 Modelling Process - Traffic Flow Simulation (Greenshields Model)

Automatically generated by Colab.

AUTHOR: Faith Paule
COURSE: BCS35
ACTIVITY: Lab 2 - Traffic Flow Modeling (Greenshields Model)

TOPIC: Computational Modeling - Traffic Flow Theory, Traffic Flow Modeling, Greenshields Model, Fundamental Diagram
OBJECTIVE
Traffic flow model based on the fundamental traffic flow theory (the relationship between density, speed, and flow). The code implements the Greenshields model, which assumes a linear relationship between speed and density. It calculates traffic flow (flow = density × speed), plots the Flow-Density curve (fundamental diagram), and finds the optimal density for maximum traffic flow.
- Model the relationship between traffic density, speed, and flow
- Apply the Greenshields linear speed-density model
- Visualize the Fundamental Diagram of Traffic Flow
- Determine optimal density for maximum traffic flow

Language & Tech Stack
Programming Language: Python 3

Tech Stack:
- NumPy: For generating a range of density values (linspace) and numerical operations.
- Matplotlib: For plotting the flow-density curve (fundamental diagram).
- Google Colab: The environment (as seen in the file path)
"""

# ============================================================================
# PART 1: BASIC TRAFFIC FLOW FUNCTION
# ============================================================================
def traffic_flow(density, speed):
    """
    Calculate traffic flow (vehicles per hour).
    Fundamental equation: Flow = Density × Speed
    
    Args:
        density: Number of vehicles per km (cars/km)
        speed: Average speed (km/h)
    
    Returns:
        Traffic flow in cars per hour
    """
    return density * speed

# Test the function with sample values
k = 20   # cars per km
v = 80   # km/h
q = traffic_flow(k, v)
print("Traffic flow:", q, "cars/hour")

# ============================================================================
# PART 2: GREENSHIELDS SPEED-DENSITY MODEL
# ============================================================================
# Greenshields Model: Linear relationship between speed and density
# v(k) = v_free × (1 - k / k_jam)
#
# Where:
# - v_free = free-flow speed (speed at zero density)
# - k_jam = jam density (density at zero speed)

v_free = 100   # Free-flow speed (km/h)
k_jam = 150    # Jam density (cars/km)

def speed_density(k):
    """
    Calculate speed using Greenshields linear model.
    
    Args:
        k: Traffic density (cars/km)
    
    Returns:
        Speed in km/h based on density
    """
    return v_free * (1 - k / k_jam)

# Test speed values at different densities
print("\nGreenshields Model: Speed vs Density")
for test_k in [0, 50, 100, 150]:
    print(f"k = {test_k:3d} cars/km → speed = {speed_density(test_k):5.1f} km/h")

# ============================================================================
# PART 3: FUNDAMENTAL DIAGRAM (Flow vs Density)
# ============================================================================
import numpy as np
import matplotlib.pyplot as plt

# Generate density values from 0 to jam density
k_values = np.linspace(0, k_jam, 100)   # 100 points for smooth curve
v_values = speed_density(k_values)       # Calculate corresponding speeds
q_values = k_values * v_values           # Flow = density × speed

# Plot the Fundamental Diagram
plt.figure(figsize=(10, 6))
plt.plot(k_values, q_values, 'b-', linewidth=2, label="Flow-Density Curve")

# Mark maximum flow point
max_flow = np.max(q_values)
best_density = k_values[np.argmax(q_values)]

plt.plot(best_density, max_flow, 'ro', markersize=10, label=f'Maximum Flow\n({max_flow:.0f} cars/h at {best_density:.1f} cars/km)')

plt.xlabel("Density (cars/km)", fontsize=12)
plt.ylabel("Flow (cars/hour)", fontsize=12)
plt.title("Fundamental Diagram of Traffic Flow (Greenshields Model)", fontsize=14)
plt.legend()
plt.grid(True, alpha=0.3)
plt.axhline(y=max_flow, color='r', linestyle='--', alpha=0.5)
plt.axvline(x=best_density, color='r', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ============================================================================
# PART 4: ANALYSIS OF RESULTS
# ============================================================================
print("\n" + "="*50)
print("TRAFFIC FLOW ANALYSIS")
print("="*50)
print(f"Maximum flow:          {max_flow:.0f} cars/hour")
print(f"Optimal density:       {best_density:.1f} cars/km")
print(f"Free-flow speed:       {v_free} km/h")
print(f"Jam density:           {k_jam} cars/km")

# Verify Greenshields properties
print(f"\nAt k = 0 (empty road):     speed = {speed_density(0):.0f} km/h (free-flow)")
print(f"At k = {k_jam} (jammed):      speed = {speed_density(k_jam):.0f} km/h (standstill)")
